# Generated by Django 4.1.8 on 2023-06-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='handle',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
