# Generated by Django 4.1.8 on 2023-05-16 11:27

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattachment',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/iMac/Documents/Backend/e-commerce/local-cdn/protected'), upload_to=products.models.handle_product_attachment_upload),
        ),
    ]
