# Generated by Django 4.1.8 on 2023-05-16 11:33

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productattachment_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattachment',
            old_name='user',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='productattachment',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/iMac/Documents/Backend/e-commerce/django/local-cdn/protected'), upload_to=products.models.handle_product_attachment_upload),
        ),
    ]
