# Generated by Django 4.1.8 on 2023-05-17 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_user_productattachment_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattachment',
            old_name='is_free',
            new_name='download_available',
        ),
    ]
