# Generated by Django 4.1.8 on 2023-05-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_is_free_productattachment_download_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattachment',
            old_name='download_available',
            new_name='is_free',
        ),
        migrations.AddField(
            model_name='productattachment',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
