# Generated by Django 4.1.8 on 2023-05-18 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_download_available_productattachment_is_free_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattachment',
            name='handle',
        ),
    ]
