# Generated by Django 4.1.8 on 2023-05-26 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productattachment'),
        ('products', '0010_product_stripe_price_id_product_stripe_product_id'),
    ]

    operations = [
    ]
