# Generated by Django 4.1.8 on 2023-06-05 01:38

import core.storages.backends
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='handle',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='productattachment',
            name='file',
            field=models.FileField(storage=core.storages.backends.ProtectedFileStorage(), upload_to=products.models.handle_product_attachment_upload),
        ),
    ]
